# This is a basic workflow to help you get started with Actions

name: Repository Secret Data

# Controls when the workflow will run
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  secretdata:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Run a multi-line script
        run:
           echo ${{secrets.USERNAME}}
           echo ${{secrets.PASSWORD}}
  dockerhblogin:
    runs-on: unbuntu-latest
    steps: 
      - name: Docker Hub Login
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USDERNAME}}
          password: ${{secrets.DOCKERHUB_TOCKEN}}
